services:
  app:
    image: 'nest.js-10.4:production'
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: production
    ports:
      - "3000:3000"
    entrypoint: node dist/main.js
